import{a as y,S as E,i as f}from"./assets/vendor-BK_rxH-O.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&n(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();y.defaults.baseURL="https://pixabay.com/api/";const S="51662095-362d68f1fb432ef34c7441ea2",p=15;function h(t,i=1){return y.get("",{params:{key:S,per_page:p,page:i,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0}})}let m,s;function b(t=[]){const i=t.map(({webformatURL:r,largeImageURL:n,tags:e,likes:o,views:l,comments:_,downloads:x})=>`
      <div class="photo-card">
        <a class="gallery__item" href="${n}">
          <img class="gallery__image" src="${r}" alt="${e}" loading="lazy" />
        </a>
        <ul class="info">
          <li><b>Likes:</b> ${o}</li>
          <li><b>Views:</b> ${l}</li>
          <li><b>Comments:</b> ${_}</li>
          <li><b>Downloads:</b> ${x}</li>
        </ul>
      </div>`).join("");gallery.insertAdjacentHTML("beforeend",i),m?m.refresh():m=new E("#gallery a",{captionsData:"alt",captionDelay:250})}function $(){const t=document.querySelector("#gallery");t&&(t.innerHTML="")}function q(){s||(s=document.createElement("div"),s.classList.add("loader","is-hidden"),s.innerHTML='<span class="loader__spinner"></span>',document.querySelector("form").insertAdjacentElement("afterend",s))}function L(){q(),s.classList.remove("is-hidden")}function v(){s&&s.classList.add("is-hidden")}function B(){moreBtn.classList.remove("is-hidden")}function d(){moreBtn.classList.add("is-hidden")}const w=document.querySelector("form"),c=w.querySelector('button[type="submit"]'),g=document.querySelector("#moreBtn");let u="",a=1;w.addEventListener("submit",async t=>{if(t.preventDefault(),u=new FormData(t.target).get("searchText").trim(),a=1,d(),!u){f.error({position:"topRight",title:"Помилка",message:"Ви нічого не ввели!"});return}const i=c.textContent;c.disabled=!0,c.textContent="Searching…",$(),L();try{const{data:r}=await h(u,a),{hits:n,totalHits:e}=r;if(console.log(`totalHits: ${e}`),n.length===0){f.warning({position:"topRight",title:"Немає результатів",message:"Нічого не знайдено."}),d();return}b(n),a*p<e?B():d()}catch(r){console.log(r),f.error({position:"topRight",title:(r==null?void 0:r.message)||"Помилка запиту",message:"Спробуйте ще раз пізніше."})}finally{v(),c.disabled=!1,c.textContent=i,t.target.reset()}});g.addEventListener("click",async()=>{g.disabled=!0,a+=1,L();try{const{data:t}=await h(u,a);b(t.hits),a*p>=t.totalHits&&d()}catch(t){console.log(t)}finally{v(),g.disabled=!1}});
//# sourceMappingURL=index.js.map
