import{a as g,S as v,i as d}from"./assets/vendor-BK_rxH-O.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();g.defaults.baseURL="https://pixabay.com/api/";const w="51662095-362d68f1fb432ef34c7441ea2",x=15;function p(t,i=1){return g.get("",{params:{key:w,per_page:x,page:i,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0}})}let u,s;function y(t=[]){const i=t.map(({webformatURL:r,largeImageURL:a,tags:e,likes:o,views:n,comments:L,downloads:P})=>`
      <div class="photo-card">
        <a class="gallery__item" href="${a}">
          <img class="gallery__image" src="${r}" alt="${e}" loading="lazy" />
        </a>
        <ul class="info">
          <li><b>Likes:</b> ${o}</li>
          <li><b>Views:</b> ${n}</li>
          <li><b>Comments:</b> ${L}</li>
          <li><b>Downloads:</b> ${P}</li>
        </ul>
      </div>`).join("");gallery.insertAdjacentHTML("beforeend",i),u?u.refresh():u=new v("#gallery a",{captionsData:"alt",captionDelay:250})}function _(){const t=document.querySelector("#gallery");t&&(t.innerHTML="")}function E(){s||(s=document.createElement("div"),s.classList.add("loader","is-hidden"),s.innerHTML='<span class="loader__spinner"></span>',document.querySelector("form").insertAdjacentElement("afterend",s))}function h(){E(),s.classList.remove("is-hidden")}function b(){s&&s.classList.add("is-hidden")}function S(){moreBtn.classList.remove("is-hidden")}function f(){moreBtn.classList.add("is-hidden")}const m=document.querySelector("form");m.textContent;const l=m.querySelector('button[type="submit"]'),$=document.querySelector("#moreBtn");let c="",B=1;m.addEventListener("submit",async t=>{if(t.preventDefault(),c=new FormData(t.target).get("searchText").trim(),!c){d.error({position:"topRight",title:"Помилка",message:"Ви нічого не ввели!"});return}const i=l.textContent;l.disabled=!0,l.textContent="Searching…",_(),h();try{const r=await p(c,B),a=r.data.hits,e=r.data.total;if(console.log(`total Img in data: ${e}`),a.length===0){d.warning({position:"topRight",title:"Немає результатів",message:"Нічого не знайдено."}),f();return}y(a),page++,e>ImgPerPage?S():f()}catch(r){console.log(r),d.error({position:"topRight",title:(r==null?void 0:r.message)||"Помилка запиту",message:"Спробуйте ще раз пізніше."})}finally{b(),l.disabled=!1,l.textContent=i,t.target.reset()}});$.addEventListener("click",async()=>{h();try{const t=await p(c,page);y(t.data.hits),page=20,page*ImgPerPage>=t.totalHits&&f()}finally{b()}});
//# sourceMappingURL=index.js.map
