import{a as p,S as P,i as u}from"./assets/vendor-BK_rxH-O.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();p.defaults.baseURL="https://pixabay.com/api/";const S="51662095-362d68f1fb432ef34c7441ea2",y=15;function h(t,n=1){return p.get("",{params:{key:S,per_page:y,page:n,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0}})}let f;const _=document.getElementById("gallery"),g=document.getElementById("loader"),b=document.getElementById("moreBtn");function L(t=[]){const n=t.map(({webformatURL:r,largeImageURL:i,tags:e,likes:o,views:a,comments:x,downloads:$})=>`
      <li class="photo-card">
        <a class="gallery__item" href="${i}">
          <img class="gallery__image" src="${r}" alt="${e}" loading="lazy" />
        </a>
        <ul class="info">
          <li><b>Likes:</b> ${o}</li>
          <li><b>Views:</b> ${a}</li>
          <li><b>Comments:</b> ${x}</li>
          <li><b>Downloads:</b> ${$}</li>
        </ul>
      </li>`).join("");_.insertAdjacentHTML("beforeend",n),f?f.refresh():f=new P("#gallery a",{captionsData:"alt",captionDelay:250})}function q(){const t=document.querySelector("#gallery");t&&(t.innerHTML="")}function B(){g.classList.remove("is-hidden")}function w(){g&&g.classList.add("is-hidden")}function v(){b.classList.remove("is-hidden")}function c(){b.classList.add("is-hidden")}const E=document.querySelector("form"),l=E.querySelector('button[type="submit"]'),m=document.querySelector("#moreBtn");let d="",s=1;E.addEventListener("submit",async t=>{if(t.preventDefault(),d=new FormData(t.target).get("searchText").trim(),s=1,c(),!d){u.error({position:"center",title:"Помилка",message:"Ви нічого не ввели!"});return}const n=l.textContent;l.disabled=!0,l.textContent="Searching…",q(),B();try{const{data:r}=await h(d,s),{hits:i,total:e}=r;if(console.log(`totalHits: ${e}`),i.length===0){u.warning({position:"center",title:"Немає результатів",message:"Нічого не знайдено."}),c();return}L(i),s*y<e?v():c()}catch(r){console.log(r),u.error({position:"center",title:(r==null?void 0:r.message)||"Помилка запиту",message:"Спробуйте ще раз пізніше."})}finally{w(),l.disabled=!1,l.textContent=n,t.target.reset()}});m.addEventListener("click",async()=>{m.disabled=!0,s+=1,B();try{const{data:t}=await h(d,s);L(t.hits),s*y>=t.total&&c()}catch(t){console.log(t)}finally{w(),m.disabled=!1}});
//# sourceMappingURL=index.js.map
